name: seismologycourse
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6.4
  - numpy>=1.15.0
  - scipy>=1.4.0
  - pandas
  - matplotlib
  - ipython
  - jupyter
  - seaborn
  - scikit-learn
  - scikit-image
  - pylops
  - cartopy
  - pip:
    - lasio
    - segyio
    - obspy
    - utm
    - pyproj
    - azure-cli